/**
 * Ticket Status State Machine
 * Defines valid transitions between ticket statuses.
 */

const TICKET_STATUSES = {
  OPEN: 'Open',
  ASSIGNED: 'Assigned',
  IN_PROGRESS: 'In Progress',
  PENDING: 'Pending',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  REOPENED: 'Reopened',
  CANCELLED: 'Cancelled',
};

// Allowed transitions: { fromStatus: [allowedToStatuses] }
const VALID_TRANSITIONS = {
  [TICKET_STATUSES.OPEN]: [TICKET_STATUSES.ASSIGNED, TICKET_STATUSES.CANCELLED],
  [TICKET_STATUSES.ASSIGNED]: [TICKET_STATUSES.IN_PROGRESS, TICKET_STATUSES.OPEN, TICKET_STATUSES.CANCELLED],
  [TICKET_STATUSES.IN_PROGRESS]: [TICKET_STATUSES.PENDING, TICKET_STATUSES.RESOLVED, TICKET_STATUSES.ASSIGNED],
  [TICKET_STATUSES.PENDING]: [TICKET_STATUSES.IN_PROGRESS, TICKET_STATUSES.RESOLVED, TICKET_STATUSES.CANCELLED],
  [TICKET_STATUSES.RESOLVED]: [TICKET_STATUSES.CLOSED, TICKET_STATUSES.REOPENED],
  [TICKET_STATUSES.CLOSED]: [],
  [TICKET_STATUSES.REOPENED]: [TICKET_STATUSES.ASSIGNED, TICKET_STATUSES.IN_PROGRESS],
  [TICKET_STATUSES.CANCELLED]: [],
};

const isValidTransition = (fromStatus, toStatus) => {
  const allowed = VALID_TRANSITIONS[fromStatus] || [];
  return allowed.includes(toStatus);
};

module.exports = { TICKET_STATUSES, VALID_TRANSITIONS, isValidTransition };
